"""empty message

Revision ID: 13484c8e7ef2
Revises: 651e308089c0
Create Date: 2020-01-04 11:46:47.615214

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13484c8e7ef2'
down_revision = '651e308089c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artist', sa.Column('seeking_venue', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Artist', 'seeking_venue')
    # ### end Alembic commands ###
