"""empty message

Revision ID: 651e308089c0
Revises: db87462744a4
Create Date: 2020-01-04 01:51:23.113356

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '651e308089c0'
down_revision = 'db87462744a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artist', sa.Column('website_link', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Artist', 'website_link')
    # ### end Alembic commands ###
